// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Teacher.proto

package com.jade.proto;

public interface TeacherRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jade.proto.TeacherRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
