// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Teacher.proto

package com.jade.proto;

public interface TeacherResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jade.proto.TeacherResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.jade.proto.TeacherResponse teacherResponse = 1;</code>
   */
  java.util.List<com.jade.proto.TeacherResponse> 
      getTeacherResponseList();
  /**
   * <code>repeated .com.jade.proto.TeacherResponse teacherResponse = 1;</code>
   */
  com.jade.proto.TeacherResponse getTeacherResponse(int index);
  /**
   * <code>repeated .com.jade.proto.TeacherResponse teacherResponse = 1;</code>
   */
  int getTeacherResponseCount();
  /**
   * <code>repeated .com.jade.proto.TeacherResponse teacherResponse = 1;</code>
   */
  java.util.List<? extends com.jade.proto.TeacherResponseOrBuilder> 
      getTeacherResponseOrBuilderList();
  /**
   * <code>repeated .com.jade.proto.TeacherResponse teacherResponse = 1;</code>
   */
  com.jade.proto.TeacherResponseOrBuilder getTeacherResponseOrBuilder(
      int index);
}
